import time

a = input("what is your name: ")
print(f"welcome to kaun banega crorepati {a}")
time.sleep(2)
print()
print("let me tell you rules of kaun banega crorepati\n1.you have to answer the questions given to you and for each correct answer you will get price displayed below")
b = ["10000", "20000", "50000", "100000", "500000", "1000000", "5000000", "10000000"]
print(b[0])
print(b[1])
print(b[2])
print(b[3])
print(b[4])
print(b[5])
print(b[6])
print(b[7])
print()
time.sleep(10)
print("for first three questions you will get 15 seconds to answer")
print()
time.sleep(5)
print("for next two questions you will get 30 seconds to answer")
print()
time.sleep(5)
print("for last three questions you will get unlimited time to answer the question")
print()
time.sleep(5)
print("2.if you face any difficulties to give answer of any question you can use three lifelines given below")
print()
time.sleep(5)
print("I. ask the audience\nyou can ask the answer of question from our audience here and they will vote for answer than you can choose answer through percentage of four options choosen by our audience")
print()
print("II. call a friend\nyou can call one of your friend from five persons given by you to management of KBC\nyou have to ask your friend the question and he will get 45 seconds to give answer")
print()
print("III. 50-50\nin this lifeline two wrong options of question will get erased by computer itself")
print()
time.sleep(10)
print("i remind you if you give wrong answer of any question you will lose everything you earned before so play carefully")
print()
time.sleep(5)
print("so let's play kaun banega crorepati")
print()
time.sleep(5)
print("your first question for ten thousand is")
print()
time.sleep(5)
print("what is the shape of the earth?")
print()
time.sleep(5)
c = ["1. rectangle", "2. triangle", "3. circle", "4. sphere"]
print(c[0])
print(c[1])
print(c[2])
print(c[3])
print()
print("your answer is: ")
d = int(input())
if(d == 4):
  print("congrats your answer is correct and you won ten thousand")
else:
  print("your answer is wrong and you have to leave the show")
  quit()
print()
time.sleep(5)
print("your second question for twenty thousand is")
print()
time.sleep(5)
print("who is the origin country of samsung company?")
print()
time.sleep(5)
e = ["1. japan", "2. scotland", "3. north corea", "4. south korea"]
print(e[0])
print(e[1])
print(e[2])
print(e[3])
print()
print("your answer is: ")
f = int(input())
if(f == 4):
  print("congrats your answer is correct and you won twenty thousand")
else:
  print("your answer is wrong and you have to leave the show")
  quit()
print()
time.sleep(5)
print("your third question for fifty thousand is")
print()
time.sleep(5)
print("what was the position of lord krishna's avatar among the ten avatars of lord vishnu?")
print()
time.sleep(5)
g = ["1. 6","2. 7","3. 8","4. 9"]
print(g[0])
print(g[1])
print(g[2])
print(g[3])
print()
print("your answer is: ")
h = int(input())
if(h == 3):
  print("congrats your answer is correct and you won fifty thousand")
else:
  print("your answer is wrong and you have to leave the show")
  quit()
print()
time.sleep(5)
print("your fourth question for one lakh is")
print()
time.sleep(5)
print("who is the currunt CEO of apple group?")
print()
time.sleep(5)
i = ["1. tim cook", "2. arthur levinson", "3. wanda austin", "4. monica lozano"]
print(i[0])
print(i[1])
print(i[2])
print(i[3])
print()
print("your answer is: ")
j = int(input())
if(j == 1):
  print("congrats your answer is correct and you won one lakh")
else:
  print("your answer is wrong and you have to leave the show")
  quit()
print()
time.sleep(5)
print("your fifth question for five lakh is")
print()
time.sleep(5)
print("who was the first indian player to score a century in ipl history?")
print()
time.sleep(5)
k = ["1. virat kohli", "2. rohit sharma", "3. virendra sehwag", "4. manish panday"]
print(k[0])
print(k[1])
print(k[2])
print(k[3])
print()
print("your answer is: ")
m = int(input())
if(m == 4):
  print("congrats your answer is correct and you won five lakh")
else:
  print("your answer is wrong and you have to leave the show")
  quit()
print()
time.sleep(5)
print("your sixth question for ten lakh is")
print()
time.sleep(5)
print("what was the name of the largest snake fossil founded in gujarat in 2005?")
print()
time.sleep(5)
n = ["1. wonambi", "2. sanajeh", "3. vasuki indicus", "4. titanoboa"]
print(n[0])
print(n[1])
print(n[2])
print(n[3])
print()
print("your answer is: ")
o = int(input())
if(o == 3):
  print("congrats your answer is correct and you won ten lakh")
else:
  print("your answer is wrong and you have to leave the show")
  quit()
print()
time.sleep(5)
print("your seventh question for fifty lakh is")
print()
time.sleep(5)
print("at what age ritesh agarwal became india's youngest self made billionaire?")
print()
time.sleep(5)
q = ["1. 23", "2. 25", "3. 21", "4. 26"]
print(q[0])
print(q[1])
print(q[2])
print(q[3])
print()
print("your answer is: ")
v = int(input())
if(v == 2):
  print("congrats your answer is correct and you won 200000")
else:
  print("your answer is wrong and you have to leave the show")
  quit()
print()
time.sleep(5)
print("your eighth question for one crore is")
print()
time.sleep(5)
print("in ICC men's T20 world cup 2016,who was player of the match in final?")
print()
time.sleep(5)
w = ["1. carlos brathwaite", "2. dwayne bravo", "3. marlon samuels", "4. chris gayle"]
print(w[0])
print(w[1])
print(w[2])
print(w[3])
print()
print("your answer is: ")
x = int(input())
if(x == 3):
  print("congrats your answer is correct and you won one crore")
else:
  print("your answer is wrong and you have to leave the show")
  quit()
print()
print("end of the show")